hdp_hdx <- function() hdp_operations('HDX / CKAN')
hdp_reliefweb <- function() hdp_operations('ReliefWeb')
hdp_who_gho <- function() hdp_operations('WHO GHO')
hdp_world_bank_health <- function() hdp_operations('World Bank Health')
hdp_unicef_sdmx <- function() hdp_operations('UNICEF SDMX')
hdp_un_sdg <- function() hdp_operations('UN SDG')
hdp_dhs <- function() hdp_operations('DHS Program')
hdp_hdx_hapi <- function() hdp_operations('HDX HAPI')
hdp_unhcr <- function() hdp_operations('UNHCR')
hdp_gdacs <- function() hdp_operations('GDACS')
